[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ctranslate2>=4.8.2",
    "dotenv>=0.9.9",
    "faster-whisper>=1.2.1",
    "numpy>=2.5.3",
    "requests>=2.34.2",
    "sounddevice>=0.5.6",
]
